### ISSUE TITLE
prompt_lean_precmd:8: bad math expression: operand expected at end of string                                                             

### ISSUE THREAD

**Issue by Brottweiler** [miekg/lean#13] opened 2016-12-15 18:01 UTC
Hello. After installing [zplug](https://github.com/zplug/zplug), I sometimes notice this error. I am not sure why it shows because of zplug, but it does, and I wanted to see if it's a bug with the lean prompt.

```sh
% zplug update
Updating...          zplug/zplug
[zplug] up-to-date (v2.3.4) a01c91fd
prompt_lean_precmd:8: bad math expression: operand expected at end of string
```

**Comment by miekg** [comment] 2016-12-15 19:25
Sometimes? Weird. I'll have to debug this yourself, I won't have time.

**Comment by Brottweiler** [comment] 2016-12-15 19:31
Sorry, I meant sometimes as in with some commands. Everytime I run `zplug update`, I see this error, if I have `zplug load --verbose` (notice the `--verbose`) in my `.zshrc`.

My idea is there's some error in the code, and you just never see this error normally, except in this situation with zplug.

**Comment by miekg** [comment] 2016-12-26 09:09
Can't reproduce, closing here.

**Closed as completed by miekg** 2016-12-26 09:09 UTC
